# Form implementation generated from reading ui file 'd:\gitprojs\new-git\CopyPasta\src\ui_files\basic.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 600)
        MainWindow.setMinimumSize(QtCore.QSize(510, 600))
        MainWindow.setMaximumSize(QtCore.QSize(510, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 20, 480, 201))
        self.scrollArea.setMinimumSize(QtCore.QSize(460, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(460, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 478, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(440, 0))
        self.frame.setMaximumSize(QtCore.QSize(440, 90))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.item_name = QtWidgets.QLabel(parent=self.frame)
        self.item_name.setMaximumSize(QtCore.QSize(100, 90))
        self.item_name.setObjectName("item_name")
        self.gridLayout.addWidget(self.item_name, 0, 0, 1, 1)
        self.item_info = QtWidgets.QTextEdit(parent=self.frame)
        self.item_info.setMinimumSize(QtCore.QSize(270, 35))
        self.item_info.setMaximumSize(QtCore.QSize(270, 35))
        self.item_info.setObjectName("item_info")
        self.gridLayout.addWidget(self.item_info, 1, 0, 1, 1)
        self.copy = QtWidgets.QPushButton(parent=self.frame)
        self.copy.setMinimumSize(QtCore.QSize(60, 30))
        self.copy.setMaximumSize(QtCore.QSize(60, 30))
        self.copy.setObjectName("copy")
        self.gridLayout.addWidget(self.copy, 1, 1, 1, 1)
        self.edit = QtWidgets.QPushButton(parent=self.frame)
        self.edit.setMaximumSize(QtCore.QSize(60, 30))
        self.edit.setObjectName("edit")
        self.gridLayout.addWidget(self.edit, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.pushButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton.setMinimumSize(QtCore.QSize(440, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(440, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.item_name.setText(_translate("MainWindow", "item_name"))
        self.copy.setText(_translate("MainWindow", "copy"))
        self.edit.setText(_translate("MainWindow", "edit"))
        self.pushButton.setText(_translate("MainWindow", "Add field"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
