# Form implementation generated from reading ui file 'd:\gitprojs\new-git\CopyPasta\src\ui_files\basic.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CopyPasta(object):
    def setupUi(self, CopyPasta):
        CopyPasta.setObjectName("CopyPasta")
        CopyPasta.resize(530, 600)
        CopyPasta.setMinimumSize(QtCore.QSize(510, 600))
        CopyPasta.setMaximumSize(QtCore.QSize(530, 600))
        self.main_window = QtWidgets.QWidget(parent=CopyPasta)
        self.main_window.setObjectName("main_window")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.main_window)
        self.scrollArea.setGeometry(QtCore.QRect(30, 20, 490, 551))
        self.scrollArea.setMinimumSize(QtCore.QSize(490, 200))
        self.scrollArea.setMaximumSize(QtCore.QSize(490, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 488, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollable = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollable.setObjectName("scrollable")
        self.add_field = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.add_field.setMinimumSize(QtCore.QSize(450, 30))
        self.add_field.setMaximumSize(QtCore.QSize(450, 30))
        self.add_field.setObjectName("add_field")
        self.scrollable.addWidget(self.add_field)
        self.basic_frame_template = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.basic_frame_template.setMinimumSize(QtCore.QSize(470, 90))
        self.basic_frame_template.setMaximumSize(QtCore.QSize(470, 90))
        self.basic_frame_template.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.basic_frame_template.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.basic_frame_template.setObjectName("basic_frame_template")
        self.gridLayout = QtWidgets.QGridLayout(self.basic_frame_template)
        self.gridLayout.setObjectName("gridLayout")
        self.item_info = QtWidgets.QTextEdit(parent=self.basic_frame_template)
        self.item_info.setMinimumSize(QtCore.QSize(240, 35))
        self.item_info.setMaximumSize(QtCore.QSize(270, 35))
        self.item_info.setObjectName("item_info")
        self.gridLayout.addWidget(self.item_info, 1, 0, 1, 1)
        self.item_name = QtWidgets.QLabel(parent=self.basic_frame_template)
        self.item_name.setMaximumSize(QtCore.QSize(100, 90))
        self.item_name.setObjectName("item_name")
        self.gridLayout.addWidget(self.item_name, 0, 0, 1, 1)
        self.copy = QtWidgets.QPushButton(parent=self.basic_frame_template)
        self.copy.setMinimumSize(QtCore.QSize(60, 30))
        self.copy.setMaximumSize(QtCore.QSize(60, 30))
        self.copy.setObjectName("copy")
        self.gridLayout.addWidget(self.copy, 1, 3, 1, 1)
        self.delete = QtWidgets.QPushButton(parent=self.basic_frame_template)
        self.delete.setMinimumSize(QtCore.QSize(60, 30))
        self.delete.setMaximumSize(QtCore.QSize(60, 30))
        self.delete.setObjectName("delete")
        self.gridLayout.addWidget(self.delete, 1, 1, 1, 1)
        self.edit = QtWidgets.QPushButton(parent=self.basic_frame_template)
        self.edit.setMinimumSize(QtCore.QSize(60, 30))
        self.edit.setMaximumSize(QtCore.QSize(60, 30))
        self.edit.setObjectName("edit")
        self.gridLayout.addWidget(self.edit, 1, 2, 1, 1)
        self.scrollable.addWidget(self.basic_frame_template)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        CopyPasta.setCentralWidget(self.main_window)

        self.retranslateUi(CopyPasta)
        QtCore.QMetaObject.connectSlotsByName(CopyPasta)

    def retranslateUi(self, CopyPasta):
        _translate = QtCore.QCoreApplication.translate
        CopyPasta.setWindowTitle(_translate("CopyPasta", "MainWindow"))
        self.add_field.setText(_translate("CopyPasta", "Add field"))
        self.item_name.setText(_translate("CopyPasta", "item_name"))
        self.copy.setText(_translate("CopyPasta", "copy"))
        self.delete.setText(_translate("CopyPasta", "delete"))
        self.edit.setText(_translate("CopyPasta", "edit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CopyPasta = QtWidgets.QMainWindow()
    ui = Ui_CopyPasta()
    ui.setupUi(CopyPasta)
    CopyPasta.show()
    sys.exit(app.exec())
